#!/usr/bin/env bash
# =============================================================================
# scan-missing-collection.sh — Scan all missing/partially-priced catalog sets
# =============================================================================
#
# Generated by: python -m src.cli.main catalog missing --user-id 3 --format script
# Date: 2026-09-18
# Updated with header + function definition by F146
#
# Usage:
#   bash scripts/scan-missing-collection.sh
#
# IMPORTANT: Must run from user's local machine (residential IP required).
#   Liga Magic blocks datacenter IPs (GitHub Actions, cloud VMs won't work).
#
# Final Fantasy set codes (Scryfall):
#   fin  — Final Fantasy (main set, 601 cards, 288 priced = 47%)
#   fic  — Final Fantasy Commander (512 cards, 511 priced = 99%) — nearly complete
#   pfin — Promo Final Fantasy (94 cards, 0 priced)
#   afin — Art Series Final Fantasy (53 cards, 0 priced)
# MYP variant mapping: eafic -> fic (in src/utils/set_code_map.py)
#
# Estimated run time (collection-priority sets, ~97 sets):
#   Total unpriced cards in collection sets: ~30,000+
#   At 5s delay, 20-card batches, 60s pause:
#     Per batch: (5s * 20 cards) + 60s pause = 160s
#     Per 100 cards: 5 batches * 160s = ~13 min
#     Full run: ~65+ hours (run in segments or overnight over multiple days)
#
# Tip: To scan only FF sets, run these lines individually:
#   scan_set "fin"    # ~313 remaining, ~2h
#   scan_set "pfin"   # 94 cards, ~25min
#   scan_set "afin"   # 53 cards, ~15min
#   (fic is already 99% complete)
#
# To regenerate this script with fresh data:
#   python -m src.cli.main catalog missing --user-id 3 --format script > scripts/scan-missing-collection.sh
# =============================================================================

set -e
cd "$(dirname "$0")/.."

CLI="python -m src.cli.main"

scan_set() {
  local code=$1
  echo ""
  echo "--- Scanning set: $code ($(date)) ---"
  $CLI catalog scan --set "$code" --delay 5 --batch-size 20 --batch-pause 60
  echo "--- Done: $code ($(date)) ---"
}

# =============================================================================
# --- Collection priority (your sets) ---
# =============================================================================
scan_set "sld"   # 2726 cards, 0 priced
scan_set "clb"   # 936 cards, 3 priced
scan_set "msc"   # 866 cards, 4 priced
scan_set "ltr"   # 858 cards, 107 priced
scan_set "j22"   # 835 cards, 2 priced
scan_set "j25"   # 779 cards, 2 priced
scan_set "cmr"   # 718 cards, 10 priced
scan_set "fin"   # 601 cards, 288 priced
scan_set "ltc"   # 585 cards, 3 priced
scan_set "2x2"   # 579 cards, 2 priced
scan_set "dft"   # 554 cards, 2 priced
scan_set "dbl"   # 535 cards, 1 priced
scan_set "rvr"   # 531 cards, 1 priced
scan_set "10e"   # 508 cards, 1 priced
scan_set "neo"   # 500 cards, 3 priced
scan_set "inr"   # 495 cards, 2 priced
scan_set "mh2"   # 492 cards, 2 priced
scan_set "dmr"   # 464 cards, 31 priced
scan_set "snc"   # 458 cards, 2 priced
scan_set "one"   # 456 cards, 2 priced
scan_set "dsk"   # 450 cards, 33 priced
scan_set "moc"   # 450 cards, 1 priced
scan_set "dmu"   # 434 cards, 3 priced
scan_set "tdm"   # 427 cards, 3 priced
scan_set "lci"   # 415 cards, 3 priced
scan_set "tdc"   # 413 cards, 3 priced
scan_set "vow"   # 412 cards, 23 priced
scan_set "khm"   # 406 cards, 4 priced
scan_set "afr"   # 402 cards, 6 priced
scan_set "eoe"   # 401 cards, 2 priced
scan_set "m3c"   # 398 cards, 2 priced
scan_set "blb"   # 397 cards, 1 priced
scan_set "eld"   # 397 cards, 6 priced
scan_set "m21"   # 397 cards, 5 priced
scan_set "mom"   # 397 cards, 27 priced
scan_set "mid"   # 391 cards, 2 priced
scan_set "znr"   # 391 cards, 2 priced
scan_set "2xm"   # 384 cards, 2 priced
scan_set "iko"   # 384 cards, 5 priced
scan_set "hob"   # 383 cards, 121 priced
scan_set "stx"   # 383 cards, 1 priced
scan_set "woe"   # 381 cards, 1 priced
scan_set "otj"   # 379 cards, 31 priced
scan_set "dsc"   # 373 cards, 1 priced
scan_set "thb"   # 358 cards, 7 priced
scan_set "c13"   # 356 cards, 2 priced
scan_set "m20"   # 345 cards, 6 priced
scan_set "afc"   # 331 cards, 3 priced
scan_set "c20"   # 322 cards, 2 priced
scan_set "m19"   # 314 cards, 9 priced
scan_set "c17"   # 309 cards, 3 priced
scan_set "c18"   # 307 cards, 2 priced
scan_set "chk"   # 307 cards, 1 priced
scan_set "c19"   # 302 cards, 2 priced
scan_set "xln"   # 289 cards, 2 priced
scan_set "ori"   # 288 cards, 1 priced
scan_set "akh"   # 287 cards, 2 priced
scan_set "m15"   # 284 cards, 1 priced
scan_set "dom"   # 280 cards, 5 priced
scan_set "kld"   # 278 cards, 1 priced
scan_set "war"   # 275 cards, 1 priced
scan_set "rtr"   # 274 cards, 1 priced
scan_set "grn"   # 273 cards, 3 priced
scan_set "rna"   # 273 cards, 2 priced
scan_set "zen"   # 269 cards, 2 priced
scan_set "dtk"   # 264 cards, 4 priced
scan_set "uma"   # 254 cards, 1 priced
scan_set "ema"   # 249 cards, 1 priced
scan_set "gtc"   # 249 cards, 2 priced
scan_set "ima"   # 249 cards, 4 priced
scan_set "m11"   # 249 cards, 2 priced
scan_set "m12"   # 249 cards, 1 priced
scan_set "m13"   # 249 cards, 1 priced
scan_set "m14"   # 249 cards, 3 priced
scan_set "mm2"   # 249 cards, 1 priced
scan_set "som"   # 249 cards, 1 priced
scan_set "ths"   # 249 cards, 1 priced
scan_set "roe"   # 248 cards, 1 priced
scan_set "avr"   # 244 cards, 3 priced
scan_set "hou"   # 209 cards, 1 priced
scan_set "emn"   # 208 cards, 1 priced
scan_set "rix"   # 205 cards, 3 priced
scan_set "frf"   # 191 cards, 1 priced
scan_set "brr"   # 189 cards, 1 priced
scan_set "voc"   # 188 cards, 3 priced
scan_set "onc"   # 174 cards, 1 priced
scan_set "sok"   # 165 cards, 1 priced
scan_set "dka"   # 158 cards, 1 priced
scan_set "hoc"   # 153 cards, 3 priced
scan_set "wwk"   # 145 cards, 2 priced
scan_set "znc"   # 142 cards, 1 priced
scan_set "e01"   # 106 cards, 1 priced
scan_set "wot"   # 103 cards, 2 priced

# =============================================================================
# --- Unscanned sets ---
# =============================================================================
scan_set "plst"   # 5579 cards
scan_set "sld"   # 2726 cards *COLL*
scan_set "who"   # 1178 cards
scan_set "9ed"   # 709 cards
scan_set "8ed"   # 707 cards
scan_set "7ed"   # 700 cards
scan_set "unf"   # 638 cards
scan_set "40k"   # 617 cards
scan_set "30a"   # 595 cards
scan_set "unk"   # 512 cards
scan_set "jmp"   # 495 cards
scan_set "5ed"   # 454 cards
scan_set "msh"   # 453 cards
scan_set "ncc"   # 447 cards
scan_set "soc"   # 426 cards
scan_set "tsr"   # 411 cards
scan_set "c21"   # 409 cards
scan_set "ecl"   # 408 cards
scan_set "tla"   # 394 cards
scan_set "mb2"   # 385 cards
scan_set "ice"   # 383 cards
scan_set "4ed"   # 378 cards
scan_set "lcc"   # 370 cards
scan_set "slz"   # 363 cards
scan_set "mkc"   # 358 cards
scan_set "blc"   # 356 cards
scan_set "inv"   # 352 cards
scan_set "ody"   # 352 cards
scan_set "scd"   # 352 cards
scan_set "c16"   # 351 cards
scan_set "ons"   # 351 cards
scan_set "mir"   # 351 cards
scan_set "mmq"   # 350 cards
scan_set "usg"   # 350 cards
scan_set "tmp"   # 350 cards
scan_set "6ed"   # 350 cards
scan_set "c15"   # 342 cards
scan_set "otc"   # 342 cards
scan_set "cma"   # 320 cards
scan_set "tmt"   # 320 cards
scan_set "cmd"   # 318 cards
scan_set "tle"   # 317 cards
scan_set "cm2"   # 312 cards
scan_set "ptc"   # 308 cards
scan_set "acr"   # 306 cards
scan_set "mrd"   # 306 cards
scan_set "rav"   # 306 cards
scan_set "3ed"   # 306 cards
scan_set "sum"   # 306 cards
scan_set "cei"   # 302 cards
scan_set "2ed"   # 302 cards
scan_set "shm"   # 302 cards
scan_set "ced"   # 302 cards
scan_set "soi"   # 302 cards
scan_set "leb"   # 302 cards
scan_set "lrw"   # 301 cards
scan_set "tsp"   # 301 cards
scan_set "bfz"   # 299 cards
scan_set "lea"   # 295 cards
scan_set "spm"   # 286 cards
scan_set "clu"   # 284 cards
scan_set "ktk"   # 269 cards
scan_set "ust"   # 268 cards
scan_set "isd"   # 264 cards
scan_set "mul"   # 260 cards
scan_set "bbd"   # 256 cards
scan_set "mh1"   # 255 cards
scan_set "ala"   # 250 cards
scan_set "a25"   # 249 cards
scan_set "mm3"   # 249 cards
scan_set "m10"   # 249 cards
scan_set "pafr"   # 241 cards
scan_set "dmc"   # 240 cards
scan_set "mat"   # 230 cards
scan_set "mma"   # 229 cards
scan_set "por"   # 228 cards
scan_set "cn2"   # 222 cards
scan_set "cns"   # 210 cards
scan_set "brc"   # 209 cards
scan_set "all"   # 199 cards
scan_set "aer"   # 197 cards
scan_set "eoc"   # 191 cards
scan_set "mic"   # 187 cards
scan_set "ogw"   # 187 cards
scan_set "fem"   # 187 cards
scan_set "drc"   # 184 cards
scan_set "pmkm"   # 180 cards
scan_set "ptk"   # 180 cards
scan_set "fut"   # 180 cards
scan_set "eve"   # 180 cards
scan_set "dis"   # 180 cards
scan_set "eos"   # 180 cards
scan_set "nec"   # 179 cards
scan_set "ecc"   # 176 cards
scan_set "nph"   # 175 cards
scan_set "s99"   # 173 cards
scan_set "pbro"   # 171 cards
scan_set "hop"   # 169 cards
scan_set "unh"   # 168 cards
scan_set "vis"   # 167 cards
scan_set "gpt"   # 167 cards
scan_set "wth"   # 167 cards
scan_set "5dn"   # 165 cards
scan_set "plc"   # 165 cards
scan_set "jou"   # 165 cards
scan_set "dst"   # 165 cards
scan_set "p02"   # 165 cards
scan_set "bng"   # 165 cards
scan_set "bok"   # 165 cards
scan_set "pstx"   # 164 cards
scan_set "spg"   # 164 cards
scan_set "amh2"   # 162 cards
scan_set "astx"   # 162 cards
scan_set "psnc"   # 161 cards
scan_set "pdmu"   # 161 cards
scan_set "potj"   # 160 cards
scan_set "peoe"   # 160 cards
scan_set "pblb"   # 160 cards
scan_set "pone"   # 160 cards
scan_set "pdft"   # 160 cards
scan_set "pdsk"   # 160 cards
scan_set "ptdm"   # 160 cards
scan_set "pwoe"   # 160 cards
scan_set "pkhm"   # 157 cards
scan_set "dgm"   # 156 cards
scan_set "pc2"   # 156 cards
scan_set "pca"   # 156 cards
scan_set "mbs"   # 155 cards
scan_set "pmid"   # 155 cards
scan_set "csp"   # 155 cards
scan_set "wc02"   # 153 cards
scan_set "pznr"   # 153 cards
scan_set "arc"   # 150 cards
scan_set "mor"   # 150 cards
scan_set "pneo"   # 148 cards
scan_set "pls"   # 146 cards
scan_set "arb"   # 145 cards
scan_set "lgn"   # 145 cards
scan_set "con"   # 145 cards
scan_set "pm20"   # 144 cards
scan_set "exo"   # 143 cards
scan_set "nem"   # 143 cards
scan_set "ulg"   # 143 cards
scan_set "jud"   # 143 cards
scan_set "tor"   # 143 cards
scan_set "scg"   # 143 cards
scan_set "apc"   # 143 cards
scan_set "sth"   # 143 cards
scan_set "pcy"   # 143 cards
scan_set "uds"   # 143 cards
scan_set "wc03"   # 142 cards
scan_set "pwar"   # 140 cards
scan_set "hml"   # 140 cards
scan_set "wc01"   # 138 cards
scan_set "peld"   # 138 cards
scan_set "pm21"   # 137 cards
scan_set "pthb"   # 137 cards
scan_set "piko"   # 137 cards
scan_set "plci"   # 136 cards
scan_set "brb"   # 136 cards
scan_set "trk"   # 135 cards
scan_set "gn3"   # 135 cards
scan_set "pmom"   # 134 cards
scan_set "gk2"   # 133 cards
scan_set "tmc"   # 132 cards
scan_set "wc97"   # 131 cards
scan_set "gk1"   # 127 cards
scan_set "chr"   # 125 cards
scan_set "drk"   # 122 cards
scan_set "tsb"   # 121 cards
scan_set "cmb1"   # 121 cards
scan_set "pvow"   # 121 cards
scan_set "cmb2"   # 121 cards
scan_set "pxln"   # 120 cards
scan_set "khc"   # 119 cards
scan_set "wc98"   # 117 cards
scan_set "pdom"   # 117 cards
scan_set "wc00"   # 117 cards
scan_set "dpa"   # 113 cards
scan_set "wc99"   # 111 cards
scan_set "pfdn"   # 106 cards
scan_set "pclb"   # 104 cards
scan_set "wc04"   # 103 cards
scan_set "atq"   # 102 cards
scan_set "mar"   # 100 cards
scan_set "prix"   # 98 cards
scan_set "und"   # 96 cards
scan_set "big"   # 95 cards
scan_set "pm19"   # 95 cards
scan_set "pfin"   # 94 cards
scan_set "arn"   # 92 cards
scan_set "pmh3"   # 92 cards
scan_set "ddj"   # 90 cards
scan_set "psoi"   # 90 cards
scan_set "pbfz"   # 90 cards
scan_set "btd"   # 90 cards
scan_set "ddm"   # 88 cards
scan_set "ugl"   # 88 cards
scan_set "pltr"   # 87 cards
scan_set "pmh2"   # 86 cards
scan_set "opca"   # 86 cards
scan_set "ath"   # 85 cards
scan_set "pgrn"   # 84 cards
scan_set "slc"   # 84 cards
scan_set "pkld"   # 83 cards
scan_set "olep"   # 83 cards
scan_set "ddn"   # 82 cards
scan_set "alci"   # 81 cards
scan_set "awoe"   # 81 cards
scan_set "aafr"   # 81 cards
scan_set "aznr"   # 81 cards
scan_set "avow"   # 81 cards
scan_set "prna"   # 81 cards
scan_set "ddg"   # 81 cards
scan_set "abro"   # 81 cards
scan_set "acmm"   # 81 cards
scan_set "asnc"   # 81 cards
scan_set "ddl"   # 81 cards
scan_set "akhm"   # 81 cards
scan_set "tcmm"   # 81 cards
scan_set "amid"   # 81 cards
scan_set "altr"   # 81 cards
scan_set "admu"   # 81 cards
scan_set "aneo"   # 81 cards
scan_set "amom"   # 81 cards
scan_set "aclb"   # 81 cards
scan_set "aone"   # 81 cards
scan_set "ddq"   # 80 cards
scan_set "ddp"   # 80 cards
scan_set "ddk"   # 80 cards
scan_set "otp"   # 80 cards
scan_set "ddh"   # 80 cards
scan_set "pecl"   # 80 cards
scan_set "ptla"   # 80 cards
scan_set "psos"   # 80 cards
scan_set "dci"   # 79 cards
scan_set "ddf"   # 79 cards
scan_set "pemn"   # 77 cards
scan_set "ddi"   # 77 cards
scan_set "pakh"   # 77 cards
scan_set "mbc"   # 77 cards
scan_set "ddu"   # 76 cards
scan_set "ddr"   # 76 cards
scan_set "pncc"   # 75 cards
scan_set "dde"   # 71 cards
scan_set "gnt"   # 68 cards
scan_set "pspm"   # 68 cards
scan_set "itp"   # 67 cards
scan_set "ddo"   # 67 cards
scan_set "amsh"   # 66 cards
scan_set "rqs"   # 65 cards
scan_set "paer"   # 65 cards
scan_set "fca"   # 65 cards
scan_set "pogw"   # 65 cards
scan_set "dds"   # 65 cards
scan_set "soa"   # 65 cards
scan_set "gn2"   # 64 cards
scan_set "twho"   # 64 cards
scan_set "ddd"   # 63 cards
scan_set "sta"   # 63 cards
scan_set "gvl"   # 63 cards
scan_set "ddt"   # 63 cards
scan_set "ddc"   # 62 cards
scan_set "dd2"   # 62 cards
scan_set "phou"   # 62 cards
scan_set "dd1"   # 62 cards
scan_set "jvc"   # 62 cards
scan_set "ulst"   # 62 cards
scan_set "evg"   # 62 cards
scan_set "dvd"   # 62 cards
scan_set "cst"   # 62 cards
scan_set "pmei"   # 61 cards
scan_set "fmsc"   # 61 cards
scan_set "phuk"   # 60 cards
scan_set "dkm"   # 58 cards
scan_set "pktk"   # 56 cards
scan_set "afdn"   # 55 cards
scan_set "aotj"   # 54 cards
scan_set "aspm"   # 54 cards
scan_set "adft"   # 54 cards
scan_set "mps"   # 54 cards
scan_set "amh3"   # 54 cards
scan_set "adsk"   # 54 cards
scan_set "atla"   # 54 cards
scan_set "aeoe"   # 54 cards
scan_set "aecl"   # 54 cards
scan_set "pori"   # 54 cards
scan_set "atmt"   # 54 cards
scan_set "asos"   # 54 cards
scan_set "mp2"   # 54 cards
scan_set "amh1"   # 54 cards
scan_set "ablb"   # 54 cards
scan_set "atdm"   # 54 cards
scan_set "slp"   # 54 cards
scan_set "afin"   # 53 cards
scan_set "punk"   # 52 cards
scan_set "tclb"   # 51 cards
scan_set "pdtk"   # 51 cards
scan_set "sch"   # 50 cards

# =============================================================================
# --- Partially scanned (<50%) ---
# =============================================================================
scan_set "pip"   # 1/1068 priced
scan_set "clb"   # 3/936 priced *COLL*
scan_set "msc"   # 4/866 priced *COLL*
scan_set "ltr"   # 107/858 priced *COLL*
scan_set "j22"   # 2/835 priced *COLL*
scan_set "j25"   # 2/779 priced *COLL*
scan_set "cmr"   # 10/718 priced *COLL*
scan_set "fin"   # 288/601 priced *COLL*
scan_set "ltc"   # 3/585 priced *COLL*
scan_set "2x2"   # 2/579 priced *COLL*
scan_set "dft"   # 2/554 priced *COLL*
scan_set "dbl"   # 1/535 priced *COLL*
scan_set "rvr"   # 1/531 priced *COLL*
scan_set "10e"   # 1/508 priced *COLL*
scan_set "neo"   # 3/500 priced *COLL*
scan_set "inr"   # 2/495 priced *COLL*
scan_set "mh2"   # 2/492 priced *COLL*
scan_set "dmr"   # 31/464 priced *COLL*
scan_set "snc"   # 2/458 priced *COLL*
scan_set "one"   # 2/456 priced *COLL*
scan_set "mkm"   # 29/453 priced
scan_set "dsk"   # 33/450 priced *COLL*
scan_set "moc"   # 1/450 priced *COLL*
scan_set "dmu"   # 3/434 priced *COLL*
scan_set "tdm"   # 3/427 priced *COLL*
scan_set "lci"   # 3/415 priced *COLL*
scan_set "tdc"   # 3/413 priced *COLL*
scan_set "vow"   # 23/412 priced *COLL*
scan_set "khm"   # 4/406 priced *COLL*
scan_set "afr"   # 6/402 priced *COLL*
scan_set "eoe"   # 2/401 priced *COLL*
scan_set "m3c"   # 2/398 priced *COLL*
scan_set "blb"   # 1/397 priced *COLL*
scan_set "eld"   # 6/397 priced *COLL*
scan_set "m21"   # 5/397 priced *COLL*
scan_set "mom"   # 27/397 priced *COLL*
scan_set "mid"   # 2/391 priced *COLL*
scan_set "znr"   # 2/391 priced *COLL*
scan_set "bro"   # 1/387 priced
scan_set "2xm"   # 2/384 priced *COLL*
scan_set "iko"   # 5/384 priced *COLL*
scan_set "hob"   # 121/383 priced *COLL*
scan_set "stx"   # 1/383 priced *COLL*
scan_set "woe"   # 1/381 priced *COLL*
scan_set "otj"   # 31/379 priced *COLL*
scan_set "dsc"   # 1/373 priced *COLL*
scan_set "sos"   # 1/368 priced
scan_set "thb"   # 7/358 priced *COLL*
scan_set "c13"   # 2/356 priced *COLL*
scan_set "m20"   # 6/345 priced *COLL*
scan_set "c14"   # 1/338 priced
scan_set "afc"   # 3/331 priced *COLL*
scan_set "c20"   # 2/322 priced *COLL*
scan_set "m19"   # 9/314 priced *COLL*
scan_set "leg"   # 1/310 priced
scan_set "c17"   # 3/309 priced *COLL*
scan_set "c18"   # 2/307 priced *COLL*
scan_set "chk"   # 1/307 priced *COLL*
scan_set "c19"   # 2/302 priced *COLL*
scan_set "xln"   # 2/289 priced *COLL*
scan_set "ori"   # 1/288 priced *COLL*
scan_set "akh"   # 2/287 priced *COLL*
scan_set "m15"   # 1/284 priced *COLL*
scan_set "dom"   # 5/280 priced *COLL*
scan_set "kld"   # 1/278 priced *COLL*
scan_set "war"   # 1/275 priced *COLL*
scan_set "rtr"   # 1/274 priced *COLL*
scan_set "grn"   # 3/273 priced *COLL*
scan_set "rna"   # 2/273 priced *COLL*
scan_set "zen"   # 2/269 priced *COLL*
scan_set "dtk"   # 4/264 priced *COLL*
scan_set "uma"   # 1/254 priced *COLL*
scan_set "ema"   # 1/249 priced *COLL*
scan_set "gtc"   # 2/249 priced *COLL*
scan_set "ima"   # 4/249 priced *COLL*
scan_set "m11"   # 2/249 priced *COLL*
scan_set "m12"   # 1/249 priced *COLL*
scan_set "m13"   # 1/249 priced *COLL*
scan_set "m14"   # 3/249 priced *COLL*
scan_set "mm2"   # 1/249 priced *COLL*
scan_set "som"   # 1/249 priced *COLL*
scan_set "ths"   # 1/249 priced *COLL*
scan_set "roe"   # 1/248 priced *COLL*
scan_set "avr"   # 3/244 priced *COLL*
scan_set "hou"   # 1/209 priced *COLL*
scan_set "emn"   # 1/208 priced *COLL*
scan_set "rix"   # 3/205 priced *COLL*
scan_set "frf"   # 1/191 priced *COLL*
scan_set "brr"   # 1/189 priced *COLL*
scan_set "voc"   # 3/188 priced *COLL*
scan_set "onc"   # 1/174 priced *COLL*
scan_set "woc"   # 1/174 priced
scan_set "sok"   # 1/165 priced *COLL*
scan_set "dka"   # 1/158 priced *COLL*
scan_set "hoc"   # 3/153 priced *COLL*
scan_set "wwk"   # 2/145 priced *COLL*
scan_set "znc"   # 1/142 priced *COLL*
scan_set "e01"   # 1/106 priced *COLL*
scan_set "wot"   # 2/103 priced *COLL*
