"""Tests for `catalog missing` CLI command (F138)."""

from __future__ import annotations

from unittest.mock import MagicMock, patch

from click.testing import CliRunner

from src.cli.main import cli


def _mock_session(catalog_rows, priced_rows, coll_rows=None):
    """Build a mock Session whose execute() returns the right rows per query."""
    call_count = 0

    def _execute(query, params=None):
        nonlocal call_count
        call_count += 1
        result = MagicMock()
        if call_count == 1:
            result.fetchall.return_value = catalog_rows
        elif call_count == 2:
            result.fetchall.return_value = priced_rows
        elif call_count == 3 and coll_rows is not None:
            result.fetchall.return_value = coll_rows
        else:
            result.fetchall.return_value = []
        return result

    session = MagicMock()
    session.execute = _execute
    return session


class TestCatalogMissingTable:
    def test_shows_unscanned_sets(self):
        runner = CliRunner()
        catalog = [("dsk", 450), ("fdn", 780), ("tiny", 10)]
        priced = [("fdn", 780)]

        session = _mock_session(catalog, priced)
        with (
            patch("src.config.get_db_url", return_value="sqlite:///test.db"),
            patch("sqlalchemy.create_engine") as mock_engine,
        ):
            mock_engine.return_value.dispose = MagicMock()
            ctx = MagicMock()
            ctx.__enter__ = lambda s: session
            ctx.__exit__ = MagicMock(return_value=False)
            mock_engine.return_value.dispose = MagicMock()
            with patch("sqlalchemy.orm.Session", return_value=ctx):
                result = runner.invoke(cli, ["catalog", "missing", "--min-cards", "50"])

        assert result.exit_code == 0
        assert "dsk" in result.output
        assert "450 cards" in result.output
        assert "tiny" not in result.output  # below min-cards
        assert "1/2 sets have price data" in result.output or "SUMMARY" in result.output

    def test_all_scanned_shows_summary(self):
        runner = CliRunner()
        catalog = [("fdn", 780)]
        priced = [("fdn", 780)]

        session = _mock_session(catalog, priced)
        with (
            patch("src.config.get_db_url", return_value="sqlite:///test.db"),
            patch("sqlalchemy.create_engine") as mock_engine,
        ):
            mock_engine.return_value.dispose = MagicMock()
            ctx = MagicMock()
            ctx.__enter__ = lambda s: session
            ctx.__exit__ = MagicMock(return_value=False)
            with patch("sqlalchemy.orm.Session", return_value=ctx):
                result = runner.invoke(cli, ["catalog", "missing"])

        assert result.exit_code == 0
        assert "UNSCANNED SETS" in result.output
        assert "1/1 sets have price data" in result.output

    def test_collection_filter(self):
        runner = CliRunner()
        catalog = [("dsk", 450), ("plst", 5579)]
        priced = []
        coll = [("dsk",)]

        session = _mock_session(catalog, priced, coll)
        with (
            patch("src.config.get_db_url", return_value="sqlite:///test.db"),
            patch("sqlalchemy.create_engine") as mock_engine,
        ):
            mock_engine.return_value.dispose = MagicMock()
            ctx = MagicMock()
            ctx.__enter__ = lambda s: session
            ctx.__exit__ = MagicMock(return_value=False)
            with patch("sqlalchemy.orm.Session", return_value=ctx):
                result = runner.invoke(
                    cli, ["catalog", "missing", "--user-id", "3", "--min-cards", "50"]
                )

        assert result.exit_code == 0
        assert "COLLECTION SETS WITHOUT PRICES (1)" in result.output
        assert "dsk" in result.output


class TestCatalogMissingScript:
    def test_script_format(self):
        runner = CliRunner()
        catalog = [("dsk", 450), ("fdn", 780)]
        priced = [("fdn", 400)]

        session = _mock_session(catalog, priced)
        with (
            patch("src.config.get_db_url", return_value="sqlite:///test.db"),
            patch("sqlalchemy.create_engine") as mock_engine,
        ):
            mock_engine.return_value.dispose = MagicMock()
            ctx = MagicMock()
            ctx.__enter__ = lambda s: session
            ctx.__exit__ = MagicMock(return_value=False)
            with patch("sqlalchemy.orm.Session", return_value=ctx):
                result = runner.invoke(
                    cli, ["catalog", "missing", "--format", "script", "--min-cards", "50"]
                )

        assert result.exit_code == 0
        assert 'scan_set "dsk"' in result.output
        assert "# Generated by:" in result.output

    def test_script_with_collection_priority(self):
        runner = CliRunner()
        catalog = [("dsk", 450), ("plst", 5579)]
        priced = []
        coll = [("dsk",)]

        session = _mock_session(catalog, priced, coll)
        with (
            patch("src.config.get_db_url", return_value="sqlite:///test.db"),
            patch("sqlalchemy.create_engine") as mock_engine,
        ):
            mock_engine.return_value.dispose = MagicMock()
            ctx = MagicMock()
            ctx.__enter__ = lambda s: session
            ctx.__exit__ = MagicMock(return_value=False)
            with patch("sqlalchemy.orm.Session", return_value=ctx):
                result = runner.invoke(
                    cli,
                    [
                        "catalog",
                        "missing",
                        "--format",
                        "script",
                        "--user-id",
                        "3",
                        "--min-cards",
                        "50",
                    ],
                )

        assert result.exit_code == 0
        assert "Collection priority" in result.output
        assert 'scan_set "dsk"' in result.output
        assert "*COLL*" in result.output
